apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBuhnA5xuW6crc28eTnbgw7PwXB3yQyxktL4Pan/QqrsGZNdcokHZGepjmfwQFN3pFedUOeghC00cXSR2O3k8PgUyBC5C+0TYLJ1/WmyHknvf8FqzeNS4N+NUciuaX8efoP1GsFdlJ+cU0nLZjUisaNnLP11LayYUg+zDgI+9UsMflOh5ALONAjKGQaOGuN6VSS0hBEk+hHOMtJd4KcO/tuhOZsW2vKP5cbUK8j6ytbj5ik4+gIupbdJpO4fscBea5ATTHzY9Hse2PuMD2liospnqLNLIb56N3zZVt5b8OIVIyYVHVVhyZiarAoTtl/ftcgkN3DQhxAgM1ey0qEyOrXxo4KReIM87m/zSzbK20AabCH6IwkWeSnw43daRHZh7N9lecbP8ksgMvr/RDhLlGo0xh9vbKkf1MvxSjAkUVL4SPr8wrX8lGFrp3FuB92GqmSIE2Zwv111JQh9iB+DVVIyI15JbWxMev7cvgpXV25aiCgtqtHyA0hiZT6d8I5POkvJ6Oo+W8Wir/rSr9mJPMI7hwPEeF/daftfS0maSLP5MjCOgrygQY/nb1Ss/ppK8KZpdIspsTCpSTcpCaFvjFaW9sHt1HBH58pzp1QItVZVs3zhzKvhVnHBjlsnKBcIuIU07Xmtmzi7cKcfvyWiTRkVEDiaWTX6nBC3VBH+jeTSW4ljPGTlDj/2OYkdckTOuWnuAv7CfKooQ==
    DB_USER: AgAMHrx9MjH3ZldYZonYrmLBjQijXIBSbyW55YY0v2Mhta95jRo+YQCjX5DWAVUovn5ifRg7mhh+BhvoNPOiaL4WVS+63cpF+aXB0BmvrFiKjlcVjKz2WF79c4IH1Vt8Pi9f6emKJHonEnz14pYuVxju1bLaPxrUP7GFJ1O0jahRjnttjOKGPUOkiaXbQhqrY8TRiRP+ecUiDGxxCEtqc1CEWfsosffJG4heL6ObMgXoVV5ljh0eV/NqCBtG7fIZ9juL4/n8Touf62ffzcFKhC2HR/hcAXiF/7R6GU8zaNX5xYJ7/r73mAGy/ebtmW4gXLKnqG9dJj+KanDtTa+iiy0WmG/r6JS1QByIiLNT0Bwuk8yfNCKi1kSY8Wu7jrMmA9jasevUhKZ7z1I1ilGcqw51RIkeaDiuIqNmjXe0ZZuetJj3GgDLXLgOgSVSbiObwenYPebN7FwaB8G9CjNDfrHTbcAvUn06/Tdx3TF3D6zswcbALDKk+kJR/KFeX7Zi5B5+lKLJR8GexukRuiHYLR0SvZKr5FMEWeLXGg1KpWNql00DThDhS5I2OIgpdvR29+udIBWcSEG0Rh1JJ/Ek4QUzYAhzZofunw90dDmOSUODEhKWeCba3KeilqkxsTvKFSs6FmyoPpPSmAtOwrbaLIzqeh3F4HfSqTAJBzcBlUr70Jr+x1DENUfonJsQu7cGwdrpyPTkDmoM+Q==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

